DLPX-85140 SDB blows up in zero-length arrays
Zero-length arrays were partially supported in SDB with the scenarios
that aren't supported blowing up the SDB session. Even though that was
rare it now occurs more often as more code uses the C99 flexible array
notation. An example is the following commit in the ZFS kernel module:

https://github.com/delphix/zfs/commit/9c8fabffa2b15a4ada570c8c469ff0709d00b003

This patch provides support for those arrays while also warning the
user that they may print garbage values if we pass their implicit
size.

I came across this failure while generating the test results for our
new reference crash dump. Fixing this issue will be the last obstacle
in generating new regression tests.

= Testing

Before:
```
$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg[2]'
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
...snip...
  File "/usr/lib/python3/dist-packages/sdb/commands/member.py", line 275, in _validate_array_index
    if type_.length <= idx:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new

$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg | array'
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
...snip...
  File "/usr/lib/python3/dist-packages/sdb/command.py", line 289, in __invalid_memory_objects_check
    obj.read_()
TypeError: cannot read object with incomplete array type
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new

$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg | array 1'
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
...snip...
  File "/usr/lib/python3/dist-packages/sdb/command.py", line 289, in __invalid_memory_objects_check
    obj.read_()
TypeError: cannot read object with incomplete array type
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

After this patch:
```
$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg[2]'
warning: member: index out of bounds for array of type 'char []' (requested index: 2)
(char)97

$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg | array'
sdb: array: zero-length array: please specify number of elements

$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg | array 1'
warning: operating on zero-length array
(char)115

$ sudo sdb -e 'zfs_dbgmsg | head 1 | member zdm_msg | array 3'
warning: operating on zero-length array
(char)115
(char)112
(char)97
```