fix: sdb requires sudo just for history file (#56) feature: allow alternate paths for history file
= Issue

Having a history file created using sudo first then trying to use SDB
on a crash dump without sudo:
```
$ sdb vmlinux-5.0.0-36-generic dump.201912060006 -s mods
Traceback (most recent call last):
  File "/usr/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 215, in main
    repl.enable_history(os.getenv('SDB_HISTORY_FILE', '~/.sdb_history'))
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 79, in enable_history
    readline.read_history_file(self.histfile)
PermissionError: [Errno 13] Permission denied
...(sdb exits)...
```

= Testing

With this patch we print a warning and drive on:
```
$ sdb vmlinux-5.0.0-36-generic dump.201912060006 -s mods
Warning: You don't have permissions to read ~/.sdb_history and
         the command history of this session won't be saved.
         Either change this files permission, recreate this file,
         or use an alternate path with the SDB_HISTORY_FILE
         environment variable.
sdb> addr spa_namespace_avl
(avl_tree_t *)spa_namespace_avl+0x0 = 0xffffffffc07d0fe0
```

Again with this patch in the same situation, we can provide an
alternative path:
```
$ SDB_HISTORY_FILE=./test-history sdb vmlinux-5.0.0-36-generic dump.201912060006 -s mods
sdb> addr init_task
(struct task_struct *)init_task+0x0 = 0xffffffff8c817740
sdb> spa
ADDR               NAME
------------------------------------------------------------
0xffffa0894e720000 data
0xffffa089413b8000 meta-domain
0xffffa08955c44000 rpool
sdb>
(^D)

$ cat test-history
addr init_task
spa

$ # running sdb with the same history file we ensure that it works
$ SDB_HISTORY_FILE=./test-history sdb vmlinux-5.0.0-36-generic dump.201912060006 -s mods
sdb> spa
ADDR               NAME
------------------------------------------------------------
0xffffa0894e720000 data
0xffffa089413b8000 meta-domain
0xffffa08955c44000 rpool
```

= Other Notes

This patch also helps with situations where SDB gets stuck because the
filesystem backing its history file has crashed and it cannot append
anything to it. For cases like these with the above patch we should
be able to get unstuck by specifying SDB_HISTORY_FILE=/dev/null, like
this:

```
$ SDB_HISTORY_FILE=/dev/null sdb vmlinux-5.0.0-36-generic dump.201912060006 -s mods
sdb> addr spa_namespace_avl
(avl_tree_t *)spa_namespace_avl+0x0 = 0xffffffffc07d0fe0
```

= Github Issue Tracker Automation

Closes #56