fix: ugly error handling when dump file doesn't exist
= Issue

Specifying a wrong argument for a crash dump shows the following error:
```
$ sdb vmlinux-5.0.0-36-generic bogus.dump -s mods
Traceback (most recent call last):
  File "/usr/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 209, in main
    prog = setup_target(args)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 157, in setup_target
    prog.set_core_dump(args.core)
FileNotFoundError: [Errno 2] No such file or directory: 'bogus.dump'
```

= Patch

With this patch:
```
$ sdb vmlinux-5.0.0-36-generic bogus.dump -s mods
sdb: no such file: 'bogus.dump'
```