Handle case of unwinding stack of running tasks
As a result of the following change in drgn, the behavior recently
changed for unwinding the stack of tasks that are in the "R" state:

    https://github.com/osandov/drgn/commit/4780c7a266

Since that change to drgn, when attempting to unwind the stack for a
running task, an exception will be raised. Here's an example:

    Traceback (most recent call last):
      File "/usr/local/bin/sdb", line 11, in <module>
        load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
      File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
        repl.start_session()
      File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
        _ = self.eval_cmd(line)
      File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
        for obj in objs:
      File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 180, in invoke
        yield from execute_pipeline(prog, first_input, pipeline)
      File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 77, in execute_pipeline
        yield from pipeline[-1].call(this_input)
      File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 226, in call
        for frame in self.prog.stack_trace(task):
    ValueError: cannot unwind stack of running task

It's expected for some tasks to be running when the "stacks" command is
used. Thus, this change adds logic to handle this exception.

Closes #55